### ISSUE TITLE
Feature request: compatibility with older Bazels

### ISSUE THREAD

**Issue by comius** [bazelbuild/rules_shell#9]
I have a problem.

- `ctx.expand_location` has been allowlisted only in recent Bazel version
- because rules_shell are now autoloaded protobuf needs to use them from github.com/bazelbuild/rules_shell
- protobuf requires support from starting Bazel 6.

Probably the best solution would be to fallback to native shell rules on older Bazel versions.

**Comment by meteorcloudy** [comment]
@fmeum Can you help with this one? This is required to make sure protobuf continues to work for older Bazel LTS versions.

**Comment by fmeum** [comment]
Sorry, I hadn't been watching this yet. I will try to add a version check.

**Comment by comius** [comment]
If you trust me to remove the rules from Bazel 8, you can just wrap them in a macro and check if native has sh_library, etc.
